# Hydra configuration for DSM-5 Criteria Classification
defaults:
  - _self_

# Data paths
data:
  translated_posts_path: "Data/translated_posts.csv"
  criteria_path: "Data/DSM-5/DSM_Criteria_Array_Fixed_Simplify.json"
  groundtruth_path: "Data/Groundtruth/criteria_evaluation.csv"

# Model parameters
model:
  max_features: 5000
  hidden_dim: 256
  dropout_rate: 0.3
  num_labels: 2

# Training parameters
training:
  num_epochs: 15
  batch_size: 64
  learning_rate: 0.001
  weight_decay: 0.01
  test_size: 0.2
  val_size: 0.1
  random_state: 42

# Output
output:
  model_dir: "./hydra_dsm_model"
  save_best_only: true

# GPU optimization
gpu:
  auto_optimize: true
  rtx_3090:
    batch_size: 128
    max_features: 8000
    num_epochs: 20
  standard_gpu:
    batch_size: 64
    max_features: 5000
    num_epochs: 15
  cpu:
    batch_size: 32
    max_features: 3000
    num_epochs: 10