# Default training configuration
num_epochs: 15
batch_size: 64
learning_rate: 0.001
weight_decay: 0.01
test_size: 0.2
val_size: 0.1
random_state: 42

# GPU-specific overrides
rtx_3090:
  batch_size: 128
  num_epochs: 20

standard_gpu:
  batch_size: 64
  num_epochs: 15

cpu:
  batch_size: 32
  num_epochs: 10