# Fast training configuration for quick testing
num_epochs: 5
batch_size: 128
learning_rate: 0.002
weight_decay: 0.01
test_size: 0.3
val_size: 0.1
random_state: 42

# GPU-specific overrides
rtx_3090:
  batch_size: 256
  num_epochs: 5

standard_gpu:
  batch_size: 128
  num_epochs: 5

cpu:
  batch_size: 64
  num_epochs: 3